name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: |
        # Configurar Surge.sh
        npm install --global surge
        surge token ebfc1230ed32e04f38dbc1608a024444
        # Desplegar en Surge.sh
        surge --project ./ --domain jennifer-contents.surge.sh 
