name: Hola Mundo CI

on:
  push:

jobs:
  notificar-y-ejecutar:
    name: Enviar notificación a ntfy.sh
    runs-on: windows-latest

    steps:
      - name: Enviar notificación
        run: |
          curl -H "Title: Nuevo push al repositorio del usuario Jennifer Espinal (2023-1411)" ^
          -H "Priority: high" ^
          -H "Authorization: Bearer ${{ secrets.API_KEY }}" ^
          -d "El usuario Jennifer Espinal (2023-1411) ha subido cambios. Ver commit: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}" ^
          https://ntfy.sh/devops-itla


